list_of_urls = [
    # "https://www.helpmefind.com/rose/plants.php?grp=A&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=B&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=C&t=2",
    "https://www.helpmefind.com/rose/plants.php?grp=D&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=E&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=F&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=G&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=H&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=I&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=J&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=K&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=L&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=M&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=N&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=O&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=P&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=Q&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=R&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=S&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=T&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=U&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=V&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=W&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=X&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=Y&t=2",
    # "https://www.helpmefind.com/rose/plants.php?grp=Z&t=2",
]
